apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-tmc-rest-api
spec:
  title: TMC REST API
  description: A workshop exploring the TMC REST API
  url: https://github.com/eduk8s-labs/lab-tmc-rest-api
  content:
    files: github.com/eduk8s-labs/lab-tmc-rest-api
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
